#!/bin/bash

if [ "$1" = "" ]
then
	echo "bruh" ; exit 1
fi

wal -c
wal -i $1 -s -e -q
pywalfox update

feh --bg-fill $1 || feh --bg-fill $1

mkdir -p $HOME/tapety/old

cp $HOME/tapety/wal.jpg $HOME/tapety/old/oldwal.jpg
convert $1 $HOME/tapety/wal.jpg

rm $HOME/.cache/wal/onebyone/* || mkdir -p $HOME/.cache/wal/onebyone

xrdb ~/.Xresources
xrdb -merge <(grep -v "depth" ~/.cache/wal/colors.Xresources | grep -v "background")
xrdb -merge <(echo "URxvt*background: [70]$(head -n 1 /home/krzych/.cache/wal/colors)")

cp $HOME/.cache/wal/colors-rofi-dark.rasi $HOME/.config/roficolor.rasi

for i in {0..15}
do
	head -n $i $HOME/.cache/wal/colors | tail -1 > $HOME/.cache/wal/onebyone/c$i
done

cp $HOME/.cache/wal/colors .

newc=$HOME/.config/tilix/schemes/despacito.json
rm "$HOME/.config/tilix/schemes/despacito.json" 2>/dev/null
c1=$(cat colors | head -n 1)
c2=$(cat colors | head -n 2 | tail -1)
c3=$(cat colors | head -n 3 | tail -1)
c4=$(cat colors | head -n 4 | tail -1)
c5=$(cat colors | head -n 5 | tail -1)
c6=$(cat colors | head -n 6 | tail -1)
c7=$(cat colors | head -n 7 | tail -1)
c8=$(cat colors | head -n 8 | tail -1)
c9=$(cat colors | head -n 9 | tail -1)
c10=$(cat colors | head -n 10 | tail -1)
c11=$(cat colors | head -n 11 | tail -1)
c12=$(cat colors | head -n 12 | tail -1)
c13=$(cat colors | head -n 13 | tail -1)
c14=$(cat colors | head -n 14 | tail -1)
c15=$(cat colors | head -n 15 | tail -1)
c16=$(cat colors | head -n 16 | tail -1)


echo "{" >> $newc
echo "	\"background-color\": \"#000000\"," >> $newc
echo "	\"badge-color\": \"#ac7ea8\"," >> $newc
echo "	\"bold-color\": \"#ffffff\"," >> $newc
echo "	\"comment\": \"autogenerated with kolor (github.com/krzysckh/kolor)\"," >> $newc
echo "	\"name\": \"$2\"," >> $newc
echo "	\"palette\": [" >> $newc
echo "		\"$c1\"," >> $newc
echo "		\"$c2\"," >> $newc
echo "		\"$c3\"," >> $newc
echo "		\"$c4\"," >> $newc
echo "		\"$c5\"," >> $newc
echo "		\"$c6\"," >> $newc
echo "		\"$c7\"," >> $newc
echo "		\"$c8\"," >> $newc
echo "		\"$c9\"," >> $newc
echo "		\"$c10\"," >> $newc
echo "		\"$c11\"," >> $newc
echo "		\"$c12\"," >> $newc
echo "		\"$c13\"," >> $newc
echo "		\"$c14\"," >> $newc
echo "		\"$c15\"," >> $newc
echo "		\"$c16\"" >> $newc
echo "	]," >> $newc
echo "	\"use-theme-colors\": true"  >> $newc
echo "}" >> $newc

rm colors

pidof bspwm > /dev/null && ( killall -9 lemonbar ; bspc wm -r )

/home/krzych/scripts/reset.sh

